---
plugins:
  - babel
env:
  node: true

parser: babel-eslint

parserOptions:
  ecmaFeatures: {
    "jsx": false
  }

extends:
  - 'airbnb-base'

rules:
  no-console: 0
  linebreak-style: 0
  no-eval: 0